import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8082/auth/realms/valtimo/protocol/openid-connect/auth?client_id=valtimo-console&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fkeycloak%2Fcallback&state=418ea7d0-8ffb-4544-a35a-afb9abfc031d&response_mode=fragment&response_type=code&scope=openid&nonce=7d27ca8a-8b35-419e-9c3a-7189f9a68c6e&code_challenge=4CFNPecu_C0yP5vb4cKVKAY924cU0u3R0jgmSRu-qKI&code_challenge_method=S256');
  await page.getByRole('textbox', { name: 'Username or email' }).click();
  await page.getByRole('textbox', { name: 'Username or email' }).fill('admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Dossiers' }).click();
  await page.getByRole('link', { name: 'Inwoner contact registratie' }).click();
  await page.getByLabel('Table action bar').getByRole('button', { name: 'Creëer Nieuw Dossier' }).click();
  await page.getByRole('button', { name: 'Start' }).click();
  await page.getByText('Anoniem').click();
  await page.getByRole('button', { name: 'Open menu' }).first().click();
  await page.getByText('Telefoongesprek').click();
  await page.getByRole('button', { name: 'Open menu' }).nth(1).click();
  await page.getByLabel('Listbox').getByText('Vraag', { exact: true }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('onderwerp');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('vraag komt hier...');
  await page.locator('#combobox-6').click();
  await page.getByText('BZ - TOZO - TONK').click();
  await page.locator('#combobox-14').click();
  await page.getByText('[BZ:5] TOZO').click();
  await page.locator('#combobox-16').click();
  await page.getByText('[BZ:5M] Betaling').click();
  await page.locator('.cds--radio-button__appearance').first().click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('antwoord komt hier...');
  await page.locator('.cds--checkbox-label').click();
  await page.waitForTimeout(1000);
  await  page.locator('v-button', { hasText: /Afronden/ }).click();
  await page.getByRole('button', { name: 'Ja' }).click();
});
